CREATE TABLE `pushrecords` (
  `id` int(11) NOT NULL auto_increment,
  `uuid` varchar(64) NOT NULL,
  `originuuid` varchar(64) NOT NULL default '',
  `destuuid` varchar(64) NOT NULL default '',
  `apicommand` varchar(128) NOT NULL default 'insert',
  `whereclause` varchar(256) NOT NULL default '',
  `destscript` varchar(256) NOT NULL default '',
  `name` varchar(128) NOT NULL default '',
  `apiusername` varchar(128) NOT NULL default '',
  `apipassword` varchar(128) NOT NULL default '',
  `port` int(11) default NULL,
  `server` varchar(255) NOT NULL default '',
  `ssl` tinyint(4) NOT NULL default '0',
  `httpformat` varchar(64) NOT NULL default 'POST',
  `dataformat` varchar(64) NOT NULL default 'json',
  `keepdestid` tinyint(1) NOT NULL default '0',
  `useuuid` tinyint(1) NOT NULL default '0',
  `dateformat` varchar(64) NOT NULL default 'SQL',
  `timeformat` varchar(64) NOT NULL default '24 Hour',
  `extraoptions` text,
  `createdby` int(11) NOT NULL default '0',
  `creationdate` datetime NOT NULL default '0000-00-00 00:00:00',
  `modifiedby` int(11) default '0',
  `modifieddate` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB;