INSERT INTO choices VALUES (101,'leadsource','Search Engine');
INSERT INTO choices VALUES (102,'leadsource','Referral');
INSERT INTO choices VALUES (103,'department','sales');
INSERT INTO choices VALUES (104,'leadsource','Other');
INSERT INTO choices VALUES (105,'leadsource','Internet');
INSERT INTO choices VALUES (106,'leadsource','Friend');
INSERT INTO choices VALUES (107,'leadsource','Book');
INSERT INTO choices VALUES (108,'paymentmethod','Personal Check');
INSERT INTO choices VALUES (109,'paymentmethod','Money Order');
INSERT INTO choices VALUES (110,'paymentmethod','Master Card');
INSERT INTO choices VALUES (111,'paymentmethod','Discover Card');
INSERT INTO choices VALUES (112,'paymentmethod','Cashiers Check');
INSERT INTO choices VALUES (113,'paymentmethod','VISA');
INSERT INTO choices VALUES (114,'paymentmethod','VISA - Debit');
INSERT INTO choices VALUES (115,'paymentmethod','Cash');
INSERT INTO choices VALUES (116,'paymentmethod','');
INSERT INTO choices VALUES (117,'shippingmethod','UPS Ground (Res)');
INSERT INTO choices VALUES (118,'shippingmethod','UPS Next Day Air');
INSERT INTO choices VALUES (119,'shippingmethod','UPS Ground (Com)');
INSERT INTO choices VALUES (120,'shippingmethod','UPS 3 Day Select');
INSERT INTO choices VALUES (121,'shippingmethod','FedEx Standard Overnight');
INSERT INTO choices VALUES (122,'paymentmethod','American Express');
INSERT INTO choices VALUES (123,'shippingmethod','UPS 2nd Day Air');
INSERT INTO choices VALUES (124,'shippingmethod','FedEx Priority Overnight AM');
INSERT INTO choices VALUES (125,'shippingmethod','');