INSERT INTO `settings` (`name`, `value`) VALUES ('shipping_markup','1.1');
INSERT INTO `settings` (`name`, `value`) VALUES ('shipping_postalcode','87124\"');
INSERT INTO `settings` (`name`, `value`) VALUES ('invoice_default_printinstruc','Thank You For Your Order.');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_payment','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_shipping','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_discount','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_taxarea','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_hascredit','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_creditlimit','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_clienttype','prospect');
INSERT INTO `settings` (`name`, `value`) VALUES ('term1_days','30');
INSERT INTO `settings` (`name`, `value`) VALUES ('term1_percentage','10');
INSERT INTO `settings` (`name`, `value`) VALUES ('term2_days','60');
INSERT INTO `settings` (`name`, `value`) VALUES ('term2_percentage','15');
INSERT INTO `settings` (`name`, `value`) VALUES ('term3_days','90');
INSERT INTO `settings` (`name`, `value`) VALUES ('term3_percentage','20');
INSERT INTO `settings` (`name`, `value`) VALUES ('prospects_on_orders','1');
INSERT INTO `settings` (`name`, `value`) VALUES ('clear_payment_on_invoice','1');