CREATE TABLE `shippingmethods` (`id` int(11) NOT NULL AUTO_INCREMENT,  `name` VARCHAR(128) NOT NULL,  `inactive` tinyint(4) DEFAULT 0,  `priority` int(11) DEFAULT 0,  `canestimate` tinyint(4) DEFAULT 0,  `estimationscript` VARCHAR(128),  `createdby` INTEGER UNSIGNED,  `creationdate` DATETIME,  `modifiedby` INTEGER UNSIGNED,  `modifieddate` TIMESTAMP, PRIMARY KEY(`id`)) ENGINE = MYISAM;
ALTER TABLE `invoices` ADD COLUMN `shippingmethodid` INTEGER UNSIGNED AFTER `shippingmethod`;
UPDATE `invoice` SET shippingmethodid=0;
ALTER TABLE `invoices` ADD COLUMN `paymentmethodid` INTEGER UNSIGNED AFTER `paymentmethod`;
UPDATE `invoice` SET paymentmethodid=0;
ALTER TABLE `invoices` ADD COLUMN `routingnumber` INTEGER UNSIGNED AFTER `paymentmethodid`;
ALTER TABLE `invoices` ADD COLUMN `accountnumber` INTEGER UNSIGNED AFTER `routingnumber`;
ALTER TABLE `invoices` ADD COLUMN `transactionid` VARCHAR(64) AFTER `accountnumber`;
INSERT INTO `tabledefs` (`id`, `displayname`, `type`, `moduleid`, `maintable`, `querytable`, `editfile`, `editroleid`, `addfile`, `addroleid`, `searchroleid`, `advsearchroleid`, `viewsqlroleid`, `deletebutton`, `defaultwhereclause`, `defaultsortorder`, `defaultsearchtype`, `defaultcriteriafindoptions`, `defaultcriteriaselection`, `createdby`, `creationdate`, `modifiedby`, `modifieddate`) VALUES (300,'Shipping Methods','table',2,'shippingmethods','shippingmethods','modules/bms/shippingmethods_addedit.php',30,'modules/bms/shippingmethods_addedit.php',30,30,30,-100,'inactivate','shippingmethods.inactive!=0','shippingmethods.priority, shippingmethods.name','','','',1,NOW(),1,NOW());
INSERT INTO `menu` (`name`, `link`, `parentid`, `displayorder`, `createdby`, `modifiedby`, `creationdate`, `modifieddate`, `roleid`) VALUES ('Shipping Methods','search.php?id=300',204,30,1,1,NOW(),NOW(),30);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (300,'All Records','shippingmethods.id!=-1',2,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (300,'Active Records','shippingmethods.inactive=0',0,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (300,'Inactive Records','shippingmethods.inactive=1',1,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (300,'new','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (300,'select','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (300,'edit','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (300,'printex','0',0,0);
INSERT INTO `tablesearchablefields` (`tabledefid`, `field`, `name`, `displayorder`, `type`) VALUES (300,'shippingmethods.name','name',0,'field');
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`,`wrap`, `size`, `format`) VALUES (300,'name','shippingmethods.name','left','',1,'',0,'99%',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`,`wrap`, `size`, `format`) VALUES (300,'estimate','shippingmethods.canestimate','center','',2,'',0,'','boolean');
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`,`wrap`, `size`, `format`) VALUES (300,'priority','shippingmethods.priority','right','',0,'',0,'',NULL);
CREATE TABLE `paymentmethods` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(128) NOT NULL default '',  `type` enum('draft','charge','receivable') default NULL,  `priority` int(8) NOT NULL default '0',  `inactive` tinyint(1) NOT NULL default '0',  `onlineprocess` tinyint(1) NOT NULL default '0',  `processscript` varchar(128) default '',  `createdby` int(11) default NULL,  `creationdate` datetime default NULL,  `modifiedby` int(11) default NULL,  `modifieddate` timestamp NOT NULL default CURRENT_TIMESTAMP,  PRIMARY KEY  (`id`)) TYPE=MyISAM PACK_KEYS=0;
INSERT INTO `tabledefs` (`id`, `displayname`, `type`, `moduleid`, `maintable`, `querytable`, `editfile`, `editroleid`, `addfile`, `addroleid`, `searchroleid`, `advsearchroleid`, `viewsqlroleid`, `deletebutton`, `defaultwhereclause`, `defaultsortorder`, `defaultsearchtype`, `defaultcriteriafindoptions`, `defaultcriteriaselection`, `createdby`, `creationdate`, `modifiedby`, `modifieddate`) VALUES (301,'Payment Methods','table',2,'paymentmethods','paymentmethods','modules/bms/paymentmethods_addedit.php',30,'modules/bms/paymentmethods_addedit.php',30,30,30,-100,'inactivate','paymentmethods.inactive=0','paymentmethods.priority,paymentmethods.name','','','',1,NOW(),1,NOW());
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (301,'All Records','paymentmethods.id!=-1',2,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (301,'Active','paymentmethods.inactive=0',0,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (301,'Inactive','paymentmethods.inactive=1',1,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (301,'new','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (301,'select','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (301,'edit','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (301,'printex','1',0,0);
INSERT INTO `tablesearchablefields` (`tabledefid`, `field`, `name`, `displayorder`, `type`) VALUES (301,'paymentmethods.name','name',0,'field');
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (301,'name','paymentmethods.name','left','',1,'',0,'99%',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (301,'type','paymentmethods.type','left','',2,'',0,'',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (301,'id','paymentmethods.id','center','',0,'',0,'',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (301,'priority','paymentmethods.priority','center','',3,'',0,'',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (301,'online process','paymentmethods.onlineprocess','center','',4,'',0,'','boolean');
INSERT INTO `menu` (`id`, `name`, `link`, `parentid`, `displayorder`, `createdby`, `modifiedby`, `creationdate`, `modifieddate`, `roleid`) VALUES (214,'Payment Methods','search.php?id=301',204,40,1,1,NOW(),NOW(),30);
ALTER TABLE `clients` ADD COLUMN `shippingmethodid` INTEGER UNSIGNED DEFAULT 0;
ALTER TABLE `clients` ADD COLUMN `paymentmethodid` INTEGER UNSIGNED DEFAULT 0;
ALTER TABLE `clients` ADD COLUMN `discountid` INTEGER UNSIGNED DEFAULT 0;
ALTER TABLE `clients` DROP `paymentmethod`;
ALTER TABLE `clients` DROP `ccnumber`;
ALTER TABLE `clients` DROP `ccexpiration`;
ALTER TABLE `clients` FROP `displayname`
ALTER TABLE `clients` ALTER COLUMN `state` `state` varchar(5) default NULL;
ALTER TABLE `clients` ALTER COLUMN `shiptostate` `shiptostate` varchar(5) default NULL;
ALTER TABLE `invoices` ALTER COLUMN `state` `state` varchar(5) default NULL;
CREATE TABLE `invoicestatuses` (`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(128), `invoicedefault` TINYINT UNSIGNED NOT NULL DEFAULT 0,`defaultassignedtoid` INTEGER UNSIGNED,`inactive` TINYINT UNSIGNED NOT NULL DEFAULT 0, `priority` INTEGER UNSIGNED NOT NULL DEFAULT 0, `createdby` INTEGER UNSIGNED, `creationdate` DATETIME, `modifiedby` INTEGER UNSIGNED, `modifieddate` TIMESTAMP, PRIMARY KEY(`id`))ENGINE = MYISAM;
CREATE TABLE `invoicestatushistory` (`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, `invoiceid` INTEGER UNSIGNED, `invoicestatusid` INTEGER UNSIGNED, `statusdate` DATE, `assignedtoid` INTEGER UNSIGNED, PRIMARY KEY(`id`))ENGINE = MYISAM;
INSERT INTO `tabledefs` (`id`, `displayname`, `type`, `moduleid`, `maintable`, `querytable`, `editfile`, `editroleid`, `addfile`, `addroleid`, `searchroleid`, `advsearchroleid`, `viewsqlroleid`, `deletebutton`, `defaultwhereclause`, `defaultsortorder`, `defaultsearchtype`, `defaultcriteriafindoptions`, `defaultcriteriaselection`, `createdby`, `creationdate`, `modifiedby`, `modifieddate`) VALUES (302,'Invoice Statuses','table',2,'invoicestatuses','invoicestatuses','modules/bms/invoicestatuses_addedit.php',30,'modules/bms/invoicestatuses_addedit.php',30,30,-100,-100,'inactivate','invoicestatuses.inactive=0','invoicestatuses.priority,invoicestatuses.name','','',''1,NOW(),1,NOW());
INSERT INTO `menu` (`id`, `name`, `link`, `parentid`, `displayorder`, `createdby`, `modifiedby`, `creationdate`, `modifieddate`, `roleid`) VALUES (215,'----','',204,15,1,1,NOW(),NOW(),30);
INSERT INTO `menu` (`id`, `name`, `link`, `parentid`, `displayorder`, `createdby`, `modifiedby`, `creationdate`, `modifieddate`, `roleid`) VALUES (216,'invoice statuses','search.php?id=302',204,50,1,1,NOW(),NOW(),30);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (302,'name','invoicestatuses.name','left','',0,'',1,'99%',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (302,'priority','invoicestatuses.priority','right','',1,'',0,'',NULL);
INSERT INTO `tablecolumns` (`tabledefid`, `name`, `column`, `align`, `footerquery`, `displayorder`, `sortorder`, `wrap`, `size`, `format`) VALUES (302,'inactive','invoicestatuses.inactive','center','',2,'',0,'','boolean');
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (302,'Active Records','invoicestatuses.inactive=0',0,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (302,'All Records','invoicestatuses.id!=-1',1,0);
INSERT INTO `tablesearchablefields` (`tabledefid`, `field`, `name`, `displayorder`, `type`) VALUES (302,'invoicestatuses.name','name',0,'field');
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (302,'new','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (302,'select','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (302,'edit','1',0,0);
INSERT INTO `tableoptions` (`tabledefid`, `name`, `option`, `othercommand`, `roleid`) VALUES (302,'printex','0',0,0);
ALTER TABLE `invoices` CHANGE COLUMN `shippeddate` `statusdate` DATE DEFAULT NULL;
ALTER TABLE `invoices` ADD COLUMN `statusid` INTEGER UNSIGNED AFTER `status`;
ALTER TABLE `invoices` ADD COLUMN `assignedtoid` INTEGER UNSIGNED AFTER `statusid`;
UPDATE `tabledefs` SET `querytable`='((invoices inner join clients on invoices.clientid=clients.id) inner join invoicestatuses on invoices.statusid=invoicestatuses.id)' WHERE `id` =3;
UPDATE `tablefindoptions` SET `search`='invoices.type=\"Order\" and invoicestatuses.name=\"Shipped / Ready To Invoice\"' WHERE `id`=24;
UPDATE `tablefindoptions` SET `search`='invoices.type=\"Order\" and invoicestatuses.name=\"Packed\"' WHERE `id`=23;
UPDATE `tablefindoptions` SET `search`='invoices.type=\"Order\" and invoicestatuses.name=\"Committed\"' WHERE `id`=106;
UPDATE `tablefindoptions` SET `search`='invoices.type=\"Order\" and invoicestatuses.name=\"Open\"' WHERE `id`=107;
ALTER TABLE `tax` ADD COLUMN `inactive` TINYINT UNSIGNED DEFAULT 0 AFTER `percentage`;
UPDATE `tabledefs` SET `defaultwhereclause`='tax.inactive=0',`deletebutton`="inactivate" WHERE `maintable`="tax";
DELETE FROM `tablefindoptions` WHERE `tabledefid`=6;
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (6,'All Records','tax.id != 0',3,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (6,'Active Records','tax.inactive=0',1,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (6,'Inactive Records','tax.inactive=1',2,0);
ALTER TABLE `productcategories` ADD COLUMN `inactive` TINYINT UNSIGNED DEFAULT 0 AFTER `name`;
UPDATE `tabledefs` SET `defaultwhereclause`='productcategories.inactive=0',`deletebutton`="inactivate" WHERE `id`=11;
DELETE FROM `tablefindoptions` WHERE `tabledefid`=11;
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (11,'All Records','productcategories.id != 0',3,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (11,'Active Records','productcategories.inactive=0',1,0);
INSERT INTO `tablefindoptions` (`tabledefid`, `name`, `search`, `displayorder`, `roleid`) VALUES (11,'Inactive Records','productcategories.inactive=1',2,0);
