INSERT INTO usersearches VALUES (31,0,3,'Orders - This Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and week(invoices.orderdate)=week(curdate())','SCH',0);
INSERT INTO usersearches VALUES (30,0,3,'Invoices - This Week','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(curdate()) and week(invoices.invoicedate)=week(curdate())','SCH',30);
INSERT INTO usersearches VALUES (29,0,3,'Invoices - Yesterday','invoices.type=\"Invoice\" and invoices.invoicedate=date_sub(curdate(),INTERVAL 1 DAY)','SCH',0);
INSERT INTO usersearches VALUES (28,0,3,'Invoices - Today','invoices.type=\"Invoice\" and invoices.invoicedate=curdate()','SCH',0);
INSERT INTO usersearches VALUES (32,0,3,'Invoices - Last Week','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.invoicedate)=week(date_sub(curdate(),INTERVAL 7 DAY))','SCH',30);
INSERT INTO usersearches VALUES (33,0,3,'Orders - Last Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.orderdate)=week(date_sub(curdate(),INTERVAL 7 DAY))','SCH',0);
INSERT INTO usersearches VALUES (34,0,3,'Invoices - This Month','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(curdate()) and month(invoices.invoicedate)=month(curdate())','SCH',30);
INSERT INTO usersearches VALUES (35,0,3,'Orders - This Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and month(invoices.orderdate)=month(curdate())','SCH',0);
INSERT INTO usersearches VALUES (36,0,3,'Invoices - Last Month','invoices.type=\"Invoice\" and year(invoicedate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoicedate)=month(date_sub(curdate(),INTERVAL 1 MONTH))','SCH',30);
INSERT INTO usersearches VALUES (37,0,3,'Orders - Last Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoices.orderdate)=month(date_sub(curdate(),INTERVAL 1 MONTH))','SCH',0);
INSERT INTO usersearches VALUES (39,0,5,'Invoices - Today','invoices.type=\"Invoice\" and invoices.invoicedate=curdate()','SCH',0);
INSERT INTO usersearches VALUES (38,0,3,'Orders - Today','invoices.type=\"Order\" and invoices.orderdate=curdate()','SCH',0);
INSERT INTO usersearches VALUES (40,0,5,'Invoices - Yesterday','invoices.type=\"Invoice\" and invoices.invoicedate=date_sub(curdate(),INTERVAL 1 DAY)','SCH',0);
INSERT INTO usersearches VALUES (41,0,5,'Invoices - This Week','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(curdate()) and week(invoices.invoicedate)=week(curdate())','SCH',30);
INSERT INTO usersearches VALUES (42,0,5,'Orders - This Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and week(invoices.orderdate)=week(curdate())','SCH',0);
INSERT INTO usersearches VALUES (43,0,5,'Invoices - Last Week','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.invoicedate)=week(date_sub(curdate(),INTERVAL 7 DAY))','SCH',30);
INSERT INTO usersearches VALUES (44,0,5,'Orders - Last Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.orderdate)=week(date_sub(curdate(),INTERVAL 7 DAY))','SCH',0);
INSERT INTO usersearches VALUES (45,0,5,'Invoices - This Month','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(curdate()) and month(invoices.invoicedate)=month(curdate())','SCH',30);
INSERT INTO usersearches VALUES (46,0,5,'Orders - This Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and month(invoices.orderdate)=month(curdate())','SCH',0);
INSERT INTO usersearches VALUES (47,0,5,'Invoices - Last Month','invoices.type=\"Invoice\" and year(invoicedate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoicedate)=month(date_sub(curdate(),INTERVAL 1 MONTH))','SCH',30);
INSERT INTO usersearches VALUES (48,0,5,'Orders - Last Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoices.orderdate)=month(date_sub(curdate(),INTERVAL 1 MONTH))','SCH',0);
INSERT INTO usersearches VALUES (49,0,5,'Orders - Today','invoices.type=\"Order\" and invoices.orderdate=curdate()','SCH',0);
INSERT INTO usersearches VALUES (70,2,2,'ID Ascending','clients.id ASC','SRT',0);