INSERT INTO tablecolumns VALUES (3,9,'id','users.id','left','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (5,9,'name','concat(users.firstname,\" \",users.lastname)','left','',1,'',0,'100%',NULL);
INSERT INTO tablecolumns VALUES (6,9,'last login','users.lastlogin','left','',4,'',0,'','datetime');
INSERT INTO tablecolumns VALUES (100,9,'log in name','users.login','left','',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (7,9,'revoked','users.revoked','center','',3,'',0,'','boolean');
INSERT INTO tablecolumns VALUES (96,11,'module','modules.name','left','',1,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (8,11,'id','tabledefs.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (9,11,'main table','tabledefs.maintable','left','',4,'',0,'100%',NULL);
INSERT INTO tablecolumns VALUES (10,11,'display','concat(\"<strong>\",tabledefs.displayname,\"</strong>\")','left','',3,'tabledefs.displayname',0,'',NULL);
INSERT INTO tablecolumns VALUES (43,11,'type','tabledefs.type','center','',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (19,10,'id','relationships.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (20,10,'name','relationships.name','left','',3,'',0,'100%',NULL);
INSERT INTO tablecolumns VALUES (92,10,'to field','relationships.tofield','left','',5,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (91,10,'from field','relationships.fromfield','left','',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (90,10,'to table','totable.displayname','left','',4,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (89,10,'from table','fromtable.displayname','left','',1,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (93,10,'inherint','relationships.inherint','center','',6,'',0,'','boolean');
INSERT INTO tablecolumns VALUES (26,16,'id','reports.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (28,16,'name','concat(\"<strong>\",reports.name,\"</strong>\")','left','reports.name',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (29,16,'type','reports.type','left','',4,'',0,'100%',NULL);
INSERT INTO tablecolumns VALUES (30,17,'id','usersearches.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (31,17,'name','usersearches.name','left','',1,'',0,'100%',NULL);
INSERT INTO tablecolumns VALUES (32,17,'user','if(usersearches.userid=0,\"<b>global</b>\",concat(users.lastname,\", \",users.firstname))','left','',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (33,17,'table','tabledefs.maintable','left','',4,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (101,17,'type','if(usersearches.type=\"SCH\",\"Search\",\"Sort\")','left','',3,'usersearches.type',0,'',NULL);
INSERT INTO tablecolumns VALUES (115,24,'id','notes.id','left','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (116,24,'start','concat(notes.startdate,\" \",notes.starttime)','left','',2,'concat(notes.startdate,\" \",notes.starttime)',0,'','datetime');
INSERT INTO tablecolumns VALUES (120,12,'done','notes.completed','center','',5,'',0,'','boolean');
INSERT INTO tablecolumns VALUES (121,12,'category','notes.category','left','',3,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (39,12,'title','notes.subject','left','',4,'',1,'90%',NULL);
INSERT INTO tablecolumns VALUES (34,12,'id','notes.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (122,23,'!','ELT(notes.importance+3,\" \",\"·\",\"-\",\"*\",\"!\",\"<b style=\'color:blue\'>!</b>\")','center','',1,'notes.importance',0,'',NULL);
INSERT INTO tablecolumns VALUES (123,23,'category','notes.category','left','',4,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (114,23,'complete','notes.completed','center','',2,'',0,'','boolean');
INSERT INTO tablecolumns VALUES (112,23,'id','notes.id','left','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (113,23,'title','notes.subject','left','',5,'',1,'90%',NULL);
INSERT INTO tablecolumns VALUES (95,21,'id','modules.id','center','',0,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (97,21,'name','modules.displayname','left','',1,'',1,'100%',NULL);
INSERT INTO tablecolumns VALUES (98,21,'version','modules.version','left','',2,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (111,16,'order','reports.displayorder','center','',3,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (117,24,'end','concat(notes.enddate,\" \",notes.endtime)','left','',3,'concat(notes.enddate,\" \",notes.endtime)',0,'','datetime');
INSERT INTO tablecolumns VALUES (118,24,'title','notes.subject','left','',5,'',1,'90%',NULL);
INSERT INTO tablecolumns VALUES (126,24,'status','notes.status','left','',6,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (119,12,'!','ELT(notes.importance+3,\"&nbsp;\",\"&middot;\",\"-\",\"*\",\"!\",\"<b style=\'color:blue\'>!</b>\")','center','',1,'notes.importance',0,'',NULL);
INSERT INTO tablecolumns VALUES (124,23,'repeat','notes.repeat','center','',3,'',0,'','boolean');
INSERT INTO tablecolumns VALUES (125,24,'!','ELT(notes.importance+3,\" \",\"·\",\"-\",\"*\",\"!\",\"<b style=\'color:blue\'>!</b>\")','center','',4,'',0,'',NULL);
INSERT INTO tablecolumns VALUES (127,24,'category','notes.category','left','',7,'',1,'',NULL);
INSERT INTO tablecolumns VALUES (128,24,'location','notes.category','left','',8,'',1,'',NULL);
INSERT INTO tablecolumns VALUES (129,24,'rpt.','if(notes.repeat,\"X\",\" \")','center','',1,'notes.repeat',0,'',NULL);
INSERT INTO tablecolumns VALUES (130,23,'due date','if(notes.endtime is not null,concat(notes.enddate,\" \",notes.endtime),notes.enddate)','left','',6,'',0,'','datetime');
INSERT INTO tablecolumns VALUES (131,12,'type','concat(\"<B>\",notes.type,\"</B>\")','center','',2,'',0,'',NULL);