INSERT INTO choices VALUES (128,'leadsource','Search Engine');
INSERT INTO choices VALUES (127,'leadsource','Referral');
INSERT INTO choices VALUES (106,'department','sales');
INSERT INTO choices VALUES (126,'leadsource','Other');
INSERT INTO choices VALUES (125,'leadsource','Internet');
INSERT INTO choices VALUES (124,'leadsource','Friend');
INSERT INTO choices VALUES (123,'leadsource','Book');
INSERT INTO choices VALUES (210,'paymentmethod','Personal Check');
INSERT INTO choices VALUES (209,'paymentmethod','Money Order');
INSERT INTO choices VALUES (208,'paymentmethod','Master Card');
INSERT INTO choices VALUES (207,'paymentmethod','Discover Card');
INSERT INTO choices VALUES (206,'paymentmethod','Cashiers Check');
INSERT INTO choices VALUES (211,'paymentmethod','VISA');
INSERT INTO choices VALUES (212,'paymentmethod','VISA - Debit');
INSERT INTO choices VALUES (213,'paymentmethod','Cash');
INSERT INTO choices VALUES (204,'paymentmethod','');
INSERT INTO choices VALUES (121,'shippingmethod','UPS Ground (Res)');
INSERT INTO choices VALUES (122,'shippingmethod','UPS Next Day Air');
INSERT INTO choices VALUES (120,'shippingmethod','UPS Ground (Com)');
INSERT INTO choices VALUES (119,'shippingmethod','UPS 3 Day Select');
INSERT INTO choices VALUES (117,'shippingmethod','FedEx Standard Overnight');
INSERT INTO choices VALUES (205,'paymentmethod','American Express');
INSERT INTO choices VALUES (118,'shippingmethod','UPS 2nd Day Air');
INSERT INTO choices VALUES (116,'shippingmethod','FedEx Priority Overnight AM');
INSERT INTO choices VALUES (115,'shippingmethod','');