CREATE TABLE clientemailprojects (
  id int(11) NOT NULL auto_increment,
  name varchar(64) default '',
  userid int(11) NOT NULL default '0',
  emailto varchar(9) NOT NULL default '',
  emailfrom varchar(128) default '',
  subject varchar(128) default '',
  body text,
  lastrun timestamp(14) NOT NULL,
  PRIMARY KEY  (id)
) TYPE=MyISAM;

CREATE TABLE clients (
  address1 varchar(128) default NULL,
  address2 varchar(128) default NULL,
  city varchar(64) default NULL,
  company varchar(128) default NULL,
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  fax varchar(32) default NULL,
  firstname varchar(64) default NULL,
  homephone varchar(32) default NULL,
  id int(11) NOT NULL auto_increment,
  lastname varchar(64) default NULL,
  leadsource varchar(64) default NULL,
  mobilephone varchar(32) default NULL,
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  otherphone varchar(32) default NULL,
  password varchar(32) default NULL,
  postalcode varchar(15) default NULL,
  salesmanagerid int(11) default NULL,
  shiptoaddress1 varchar(128) default NULL,
  shiptoaddress2 varchar(128) default NULL,
  shiptocity varchar(64) default NULL,
  shiptopostalcode varchar(15) default NULL,
  shiptostate char(2) default NULL,
  state char(2) default NULL,
  username varchar(32) default NULL,
  workphone varchar(32) default NULL,
  inactive tinyint(4) NOT NULL default '0',
  type enum('prospect','client') NOT NULL default 'prospect',
  email varchar(128) default NULL,
  webaddress varchar(128) default NULL,
  comments text,
  paymentmethod varchar(64) default NULL,
  ccnumber varchar(64) default NULL,
  ccexpiration varchar(64) default NULL,
  displayname varchar(128) default NULL,
  country varchar(64) default '',
  shiptocountry varchar(64) default '',
  category varchar(128) default NULL,
  becameclient date default NULL,
  UNIQUE KEY theid (id),
  KEY notin (inactive),
  KEY thefirstname (firstname),
  KEY address (address1),
  KEY zip (postalcode),
  KEY created (creationdate),
  KEY thelastname (lastname),
  KEY thecompany (company),
  KEY thetype (type)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE discounts (
  id int(11) NOT NULL auto_increment,
  name varchar(128) default '',
  inactive tinyint(1) NOT NULL default '0',
  type enum('percent','amount') NOT NULL default 'percent',
  value double NOT NULL default '0',
  description text,
  createdby int(11) default NULL,
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  creationdate datetime default NULL,
  PRIMARY KEY  (id)
) TYPE=MyISAM;

CREATE TABLE invoices (
  address1 varchar(128) default NULL,
  address2 varchar(128) default NULL,
  bankname varchar(64) default NULL,
  ccexpiration varchar(10) default NULL,
  ccnumber varchar(64) default NULL,
  checkno varchar(32) default NULL,
  city varchar(64) default NULL,
  clientid int(11) NOT NULL default '0',
  id int(11) NOT NULL auto_increment,
  invoicedate date default NULL,
  leadsource varchar(64) default NULL,
  orderdate date default NULL,
  paymentmethod varchar(64) default NULL,
  postalcode varchar(15) default NULL,
  printedinstructions text,
  shippeddate date default NULL,
  shipping double default '0',
  shippingmethod varchar(64) default NULL,
  specialinstructions text,
  state char(2) default NULL,
  type enum('Quote','Order','Invoice','VOID') default NULL,
  tax double default '0',
  taxareaid int(11) default '0',
  totalti double default '0',
  totaltni double default '0',
  totalweight double default '0',
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  amountpaid double default '0',
  totalcost double default '0',
  trackingno varchar(64) default NULL,
  weborder tinyint(1) default '0',
  webconfirmationno varchar(64) default '',
  ccverification varchar(4) default '',
  country varchar(64) default '',
  ponumber varchar(64) default NULL,
  requireddate date default NULL,
  taxpercentage double default NULL,
  totaltaxable double NOT NULL default '0',
  discountamount double NOT NULL default '0',
  status enum('Open','Committed','Packed','Shipped') default NULL,
  discountid int(11) NOT NULL default '0',
  UNIQUE KEY theid (id),
  KEY client (clientid)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE lineitems (
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  id int(11) NOT NULL auto_increment,
  invoiceid int(11) NOT NULL default '0',
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  productid int(11) default NULL,
  quantity double default NULL,
  unitcost double default NULL,
  unitprice double default NULL,
  unitweight double default NULL,
  memo text,
  taxable tinyint(4) NOT NULL default '1',
  UNIQUE KEY theid (id),
  KEY invoice (invoiceid),
  KEY product (productid)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE prerequisites (
  childid int(11) NOT NULL default '0',
  id int(11) NOT NULL auto_increment,
  parentid int(11) NOT NULL default '0',
  UNIQUE KEY theid (id),
  KEY child (childid),
  KEY parent (parentid)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE productcategories (
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  description text,
  id int(11) NOT NULL auto_increment,
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  name varchar(64) default NULL,
  webenabled tinyint(1) NOT NULL default '0',
  webdisplayname varchar(64) default '',
  UNIQUE KEY theid (id)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE products (
  categoryid int(11) NOT NULL default '0',
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  description varchar(255) default NULL,
  id int(11) NOT NULL auto_increment,
  isoversized tinyint(4) NOT NULL default '0',
  isprepackaged tinyint(4) NOT NULL default '0',
  packagesperitem double default NULL,
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  partname varchar(128) default NULL,
  partnumber varchar(32) NOT NULL default '',
  status varchar(32) NOT NULL default 'In Stock',
  unitcost double default '0',
  unitofmeasure varchar(64) default NULL,
  unitprice double default '0',
  weight double default NULL,
  webenabled tinyint(1) NOT NULL default '0',
  keywords varchar(128) default NULL,
  thumbnail mediumblob,
  thumbnailmime varchar(128) default NULL,
  picture mediumblob,
  picturemime varchar(128) default NULL,
  webdescription text,
  inactive tinyint(4) NOT NULL default '0',
  type enum('Inventory','Non-Inventory','Service','Kit','Assembly') NOT NULL default 'Inventory',
  taxable tinyint(4) NOT NULL default '1',
  memo text,
  upc varchar(128) default NULL,
  UNIQUE KEY theid (id),
  UNIQUE KEY thpartnum (partnumber),
  KEY status (status)
) TYPE=MyISAM PACK_KEYS=0;

CREATE TABLE tax (
  id int(11) NOT NULL auto_increment,
  name varchar(64) default NULL,
  percentage double NOT NULL default '0',
  createdby int(11) NOT NULL default '0',
  creationdate datetime NOT NULL default '0000-00-00 00:00:00',
  modifiedby int(11) default NULL,
  modifieddate timestamp(14) NOT NULL,
  UNIQUE KEY theid (id)
) TYPE=MyISAM PACK_KEYS=0;