INSERT INTO tableoptions VALUES (1,2,'new','1',0,0);
INSERT INTO tableoptions VALUES (2,2,'edit','1',0,0);
INSERT INTO tableoptions VALUES (3,2,'printex','1',0,0);
INSERT INTO tableoptions VALUES (4,2,'select','1',0,0);
INSERT INTO tableoptions VALUES (5,2,'mark_asclient','convert to client',1,0);
INSERT INTO tableoptions VALUES (6,2,'stamp_infosent','info packet sent',1,0);
INSERT INTO tableoptions VALUES (7,2,'delete_prospects','delete prospects',1,0);
INSERT INTO tableoptions VALUES (28,3,'new','1',0,20);
INSERT INTO tableoptions VALUES (29,3,'select','1',0,0);
INSERT INTO tableoptions VALUES (30,3,'edit','1',0,0);
INSERT INTO tableoptions VALUES (31,3,'printex','1',0,0);
INSERT INTO tableoptions VALUES (32,3,'mark_aspaid','mark paid in full',1,0);
INSERT INTO tableoptions VALUES (33,3,'mark_asinvoice','convert to invoice',1,30);
INSERT INTO tableoptions VALUES (34,3,'mark_ashipped','mark as shipped',1,0);
INSERT INTO tableoptions VALUES (35,5,'new','0',0,0);
INSERT INTO tableoptions VALUES (36,5,'select','1',0,0);
INSERT INTO tableoptions VALUES (37,5,'edit','0',0,0);
INSERT INTO tableoptions VALUES (38,6,'new','1',0,0);
INSERT INTO tableoptions VALUES (39,6,'select','1',0,0);
INSERT INTO tableoptions VALUES (40,6,'edit','1',0,0);
INSERT INTO tableoptions VALUES (41,4,'new','1',0,0);
INSERT INTO tableoptions VALUES (42,4,'edit','1',0,0);
INSERT INTO tableoptions VALUES (43,4,'select','1',0,0);
INSERT INTO tableoptions VALUES (44,4,'printex','1',0,0);
INSERT INTO tableoptions VALUES (45,7,'new','1',0,0);
INSERT INTO tableoptions VALUES (46,7,'edit','1',0,0);
INSERT INTO tableoptions VALUES (47,7,'select','1',0,0);
INSERT INTO tableoptions VALUES (48,7,'printex','1',0,0);
INSERT INTO tableoptions VALUES (49,8,'new','0',0,0);
INSERT INTO tableoptions VALUES (50,8,'select','1',0,0);
INSERT INTO tableoptions VALUES (51,8,'edit','0',0,0);
INSERT INTO tableoptions VALUES (52,18,'new','0',0,0);
INSERT INTO tableoptions VALUES (53,18,'edit','0',0,0);
INSERT INTO tableoptions VALUES (54,18,'select','1',0,0);
INSERT INTO tableoptions VALUES (55,18,'delete_prospects','delete prospects',0,0);
INSERT INTO tableoptions VALUES (63,2,'massEmail','send mass e-mail',1,0);
INSERT INTO tableoptions VALUES (64,22,'new','0',0,0);
INSERT INTO tableoptions VALUES (65,22,'edit','1',0,0);
INSERT INTO tableoptions VALUES (66,22,'select','1',0,0);
INSERT INTO tableoptions VALUES (67,22,'printex','0',0,0);
INSERT INTO tableoptions VALUES (68,5,'printex','1',0,0);
INSERT INTO tableoptions VALUES (79,3,'mark_asuninvoice','remove invoice status',1,90);
INSERT INTO tableoptions VALUES (80,25,'new','1',0,-10);
INSERT INTO tableoptions VALUES (81,25,'select','1',0,-10);
INSERT INTO tableoptions VALUES (82,25,'edit','1',0,-10);