INSERT INTO tablefindoptions VALUES (1,2,'Prospects','clients.type = \"prospect\"   and clients.inactive=0',1,0);
INSERT INTO tablefindoptions VALUES (49,3,'Invoices - Today','invoices.type=\"Invoice\" and invoices.invoicedate=curdate()',9,20);
INSERT INTO tablefindoptions VALUES (50,3,'Invoices - Yesterday','invoices.type=\"Invoice\" and invoices.invoicedate=date_sub(curdate(),INTERVAL 1 DAY)',10,20);
INSERT INTO tablefindoptions VALUES (7,2,'Today\'s Prospects','clients.type = \"prospect\" and (TO_DAYS(now())-TO_DAYS(clients.creationdate))=0 and clients.inactive=0',3,0);
INSERT INTO tablefindoptions VALUES (8,2,'Yesterday\'s Prospects','clients.type = \"prospect\" and (TO_DAYS(now())-TO_DAYS(clients.creationdate)=1 and clients.inactive=0',4,0);
INSERT INTO tablefindoptions VALUES (9,2,'Last Week\'s Prospects','clients.type = \"prospect\" and (TO_DAYS(now())-TO_DAYS(clients.creationdate))<7 and clients.inactive=0',5,0);
INSERT INTO tablefindoptions VALUES (10,2,'Clients','clients.type = \"client\" and clients.inactive=0',0,0);
INSERT INTO tablefindoptions VALUES (11,2,'Inactive Clients','clients.type = \"client\" and clients.inactive=1',6,0);
INSERT INTO tablefindoptions VALUES (12,2,'All Records','clients.id != 0',7,0);
INSERT INTO tablefindoptions VALUES (45,3,'Invoices - This Month','invoices.type=\"Invoice\" and year(invoicedate)=year(curdate()) and month(invoicedate)=month(curdate())',13,30);
INSERT INTO tablefindoptions VALUES (22,3,'Orders','invoices.type=\"Order\"',1,-10);
INSERT INTO tablefindoptions VALUES (23,3,'Orders - Packed','invoices.type=\"Order\" and invoices.status=\"Packed\"',4,-10);
INSERT INTO tablefindoptions VALUES (24,3,'Orders - Shipped','invoices.type=\"Order\" and invoices.status=\"Shipped\"',5,-10);
INSERT INTO tablefindoptions VALUES (25,3,'Invoices','invoices.type=\"Invoice\"',8,30);
INSERT INTO tablefindoptions VALUES (26,3,'Quotes','invoices.type=\"Quote\"',7,20);
INSERT INTO tablefindoptions VALUES (27,3,'Voided Records','invoices.type=\"VOID\"',18,-10);
INSERT INTO tablefindoptions VALUES (28,3,'All Records','invoices.id != 0',19,30);
INSERT INTO tablefindoptions VALUES (29,5,'All Records','lineitems.id!=0',0,30);
INSERT INTO tablefindoptions VALUES (30,6,'All Records','tax.id != 0',1,0);
INSERT INTO tablefindoptions VALUES (31,4,'In Stock Items','products.status=\"In Stock\"',1,0);
INSERT INTO tablefindoptions VALUES (32,4,'Out of Stock Items','products.status=\"Out of Stock\"',2,0);
INSERT INTO tablefindoptions VALUES (33,4,'Backordered Items','products.status=\"Backordered\"',3,0);
INSERT INTO tablefindoptions VALUES (34,4,'Inactive','products.inactive=1',4,-10);
INSERT INTO tablefindoptions VALUES (35,4,'All Records','products.id != 0',5,0);
INSERT INTO tablefindoptions VALUES (36,7,'All Records','productcategories.id != 0',1,0);
INSERT INTO tablefindoptions VALUES (37,8,'All Records','prerequisites.id != 0',1,0);
INSERT INTO tablefindoptions VALUES (38,18,'matching names','clients.firstname=dupclients.firstname and clients.lastname=dupclients.lastname and clients.id<>dupclients.ID',1,0);
INSERT INTO tablefindoptions VALUES (39,18,'Matching Names and Postal Code','clients.firstname=dupclients.firstname and clients.lastname=dupclients.lastname and clients.postalcode=dupclients.postalcode and clients.id<>dupclients.ID',2,0);
INSERT INTO tablefindoptions VALUES (40,18,'Matching Addresses','clients.address1=dupclients.address1 and clients.id<>dupclients.ID',3,0);
INSERT INTO tablefindoptions VALUES (41,18,'Matching Home Phone','clients.homephone=dupclients.homephone and clients.id<>dupclients.ID',4,0);
INSERT INTO tablefindoptions VALUES (46,3,'Invoices - Last Month','invoices.type=\"Invoice\" and year(invoicedate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoicedate)=month(date_sub(curdate(),INTERVAL 1 MONTH))',14,30);
INSERT INTO tablefindoptions VALUES (47,22,'all records','clientemailprojects.id!=-1',0,0);
INSERT INTO tablefindoptions VALUES (48,22,'global projects','clientemailprojects.userid=0',1,0);
INSERT INTO tablefindoptions VALUES (51,3,'Invoices - This Week','invoices.type=\"Invoice\" and year(invoicedate)=year(curdate()) and week(invoicedate)=week(curdate())',11,30);
INSERT INTO tablefindoptions VALUES (52,3,'Invoices - Last Week','invoices.type=\"Invoice\" and year(invoicedate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoicedate)=week(date_sub(curdate(),INTERVAL 7 DAY))',12,30);
INSERT INTO tablefindoptions VALUES (53,3,'Orders - Today','invoices.type=\"Order\" and invoices.orderdate=curdate()',6,-10);
INSERT INTO tablefindoptions VALUES (54,5,'Orders','invoices.type=\"Order\"',1,0);
INSERT INTO tablefindoptions VALUES (55,5,'Quotes','invoices.type=\"Quote\"',8,0);
INSERT INTO tablefindoptions VALUES (56,5,'Invoices','invoices.type=\"Invoice\"',9,30);
INSERT INTO tablefindoptions VALUES (57,5,'Orders - Today','invoices.type=\"Order\" and invoices.orderdate=curdate()',2,0);
INSERT INTO tablefindoptions VALUES (58,5,'Invoices - Yesterday','invoices.type=\"Invoice\" and invoices.invoicedate=date_sub(curdate(),INTERVAL 1 DAY)',11,0);
INSERT INTO tablefindoptions VALUES (59,5,'Orders - Yesterday','invoices.type=\"Orders\" and invoices.orderdate=date_sub(curdate(),INTERVAL 1 DAY)',3,0);
INSERT INTO tablefindoptions VALUES (60,5,'Orders - Last Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.orderdate)=week(date_sub(curdate(),INTERVAL 7 DAY))',5,0);
INSERT INTO tablefindoptions VALUES (61,5,'Orders - This Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and week(invoices.orderdate)=week(curdate())',4,0);
INSERT INTO tablefindoptions VALUES (62,5,'Orders - This Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and month(invoices.orderdate)=month(curdate())',6,0);
INSERT INTO tablefindoptions VALUES (63,5,'Orders - Last Month','invoices.type=\"Order\" and year(invoices.orderdate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoices.orderdate)=month(date_sub(curdate(),INTERVAL 1 MONTH))',7,0);
INSERT INTO tablefindoptions VALUES (64,5,'Invoices - Today','invoices.type=\"Invoice\" and invoices.invoicedate=curdate()',10,0);
INSERT INTO tablefindoptions VALUES (65,5,'Invoices - This Week','invoices.type=\"Order\" and year(invoices.orderdate)=year(curdate()) and week(invoices.orderdate)=week(curdate())',12,30);
INSERT INTO tablefindoptions VALUES (66,5,'Invoices - Last Week','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(date_sub(curdate(),INTERVAL 7 DAY)) and week(invoices.invoicedate)=week(date_sub(curdate(),INTERVAL 7 DAY))',13,30);
INSERT INTO tablefindoptions VALUES (67,5,'Invoices - This Month','invoices.type=\"Invoice\" and year(invoices.invoicedate)=year(curdate()) and month(invoices.invoicedate)=month(curdate())',14,30);
INSERT INTO tablefindoptions VALUES (68,5,'Invoices - Last Month','invoices.type=\"Invoice\" and year(invoicedate)=year(date_sub(curdate(),INTERVAL 1 MONTH)) and month(invoicedate)=month(date_sub(curdate(),INTERVAL 1 MONTH))',15,30);
INSERT INTO tablefindoptions VALUES (105,25,'all records','discounts.id!=0',0,-10);
INSERT INTO tablefindoptions VALUES (102,3,'Invoices - This Quarter','invoices.type=\"Invoice\" AND YEAR(invoices.invoicedate)=YEAR(CURDATE()) and QUARTER(invoices.invoicedate)=QUARTER(CURDATE())',15,30);
INSERT INTO tablefindoptions VALUES (103,3,'Invoices - This Year','invoices.type=\"Invoice\" AND YEAR(invoices.invoicedate)=YEAR(CURDATE())',17,30);
INSERT INTO tablefindoptions VALUES (104,3,'Invoices - Last Quarter','invoices.type=\"Invoice\" AND YEAR(invoices.invoicedate)=YEAR(DATE_SUB(CURDATE(),INTERVAL 3 MONTH)) and QUARTER(invoices.invoicedate)=QUARTER(DATE_SUB(CURDATE(),INTERVAL 3 MONTH))',16,30);
INSERT INTO tablefindoptions VALUES (106,3,'Orders - Committed','invoices.type=\"Order\" and invoices.status=\"Committed\"',3,-10);
INSERT INTO tablefindoptions VALUES (107,3,'Orders - Open','invoices.type=\"Order\" and invoices.status=\"Open\"',2,-10);