INSERT INTO tablesearchablefields VALUES (1,2,'(clients.lastname like \"{{value}}%\" or clients.firstname like \"{{value}}%\" or clients.company like \"{{value}}%\")','company / name',0,'whereclause');
INSERT INTO tablesearchablefields VALUES (14,2,'(clients.homephone like \"{{value}}%\" or clients.workphone like \"{{value}}%\" or clients.mobilephone like \"{{value}}%\" or clients.otherphone like \"{{value}}%\" or clients.fax like \"{{value}}%\")','phone',1,'whereclause');
INSERT INTO tablesearchablefields VALUES (17,2,'clients.city','city',2,'field');
INSERT INTO tablesearchablefields VALUES (18,2,'clients.state','state',3,'field');
INSERT INTO tablesearchablefields VALUES (19,2,'clients.postalcode','postal code',4,'field');
INSERT INTO tablesearchablefields VALUES (20,2,'clients.email','e-mail',5,'field');
INSERT INTO tablesearchablefields VALUES (21,2,'clients.leadsource','lead source',6,'field');
INSERT INTO tablesearchablefields VALUES (22,2,'clients.id','id',7,'field');
INSERT INTO tablesearchablefields VALUES (72,3,'invoices.orderdate','order date',2,'field');
INSERT INTO tablesearchablefields VALUES (73,3,'invoices.invoicedate','invoice date',3,'field');
INSERT INTO tablesearchablefields VALUES (40,3,'(clients.lastname like \"{{value}}%\" or clients.firstname like \"{{value}}%\" or clients.company like \"{{value}}%\")','company / name',1,'whereclause');
INSERT INTO tablesearchablefields VALUES (41,3,'invoices.id','id',0,'field');
INSERT INTO tablesearchablefields VALUES (48,4,'products.partnumber','part number',0,'field');
INSERT INTO tablesearchablefields VALUES (49,4,'products.partname','part name',1,'field');
INSERT INTO tablesearchablefields VALUES (50,4,'products.unitprice','unit price',2,'field');
INSERT INTO tablesearchablefields VALUES (51,4,'products.id','id',3,'field');
INSERT INTO tablesearchablefields VALUES (42,5,'products.partnumber','part number',0,'field');
INSERT INTO tablesearchablefields VALUES (43,5,'lineitems.invoiceid','invoice id',2,'field');
INSERT INTO tablesearchablefields VALUES (44,5,'lineitems.id','id',8,'field');
INSERT INTO tablesearchablefields VALUES (76,5,'invoices.orderdate','order date',3,'field');
INSERT INTO tablesearchablefields VALUES (77,5,'invoices.invoicedate','invoice date',4,'field');
INSERT INTO tablesearchablefields VALUES (45,5,'products.partname','part name',1,'field');
INSERT INTO tablesearchablefields VALUES (46,6,'tax.name','name',0,'field');
INSERT INTO tablesearchablefields VALUES (47,6,'tax.id','id',1,'field');
INSERT INTO tablesearchablefields VALUES (52,7,'productcategories.name','name',0,'field');
INSERT INTO tablesearchablefields VALUES (53,7,'productcategories.id','id',1,'field');
INSERT INTO tablesearchablefields VALUES (54,8,'products.partnumber','part number',0,'field');
INSERT INTO tablesearchablefields VALUES (55,8,'products.partname','part name',1,'field');
INSERT INTO tablesearchablefields VALUES (56,8,'childproducts.partnumber','dependent part number',2,'field');
INSERT INTO tablesearchablefields VALUES (57,8,'childproducts.partname','dependent name',3,'field');
INSERT INTO tablesearchablefields VALUES (58,8,'prerequisites.id','id',4,'field');
INSERT INTO tablesearchablefields VALUES (59,18,'(clients.lastname like \"{{value}}%\" or clients.firstname like \"{{value}}%\" or clients.company like \"{{value}}%\")','company / name',0,'whereclause');
INSERT INTO tablesearchablefields VALUES (61,18,'(clients.homephone like \"{{value}}%\" or clients.workphone like \"{{value}}%\" or clients.mobilephone like \"{{value}}%\" or clients.otherphone like \"{{value}}%\" or clients.fax like \"{{value}}%\")','phone',1,'whereclause');
INSERT INTO tablesearchablefields VALUES (62,18,'clients.city','city',2,'field');
INSERT INTO tablesearchablefields VALUES (63,18,'clients.state','state',3,'field');
INSERT INTO tablesearchablefields VALUES (64,18,'clients.postalcode','postal code',4,'field');
INSERT INTO tablesearchablefields VALUES (65,18,'clients.email','e-mail',5,'field');
INSERT INTO tablesearchablefields VALUES (66,18,'clients.id','id',6,'field');
INSERT INTO tablesearchablefields VALUES (74,22,'clientemailprojects.name','name',0,'field');
INSERT INTO tablesearchablefields VALUES (75,22,'users.firstname like \"{{value}}%\" or users.lastname like \"{{value}}%\"','user',1,'whereclause');
INSERT INTO tablesearchablefields VALUES (95,25,'discounts.name','name',0,'field');