INSERT INTO `settings` (`name`, `value`) VALUES ('application_name','phpBMS');
INSERT INTO `settings` (`name`, `value`) VALUES ('encryption_seed','freeble');
INSERT INTO `settings` (`name`, `value`) VALUES ('record_limit','45');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_load_page','modules/base/snapshot.php');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_name','Kreotek LLC');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_address','481 Rio Rancho Blvd. NE ');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_csz','Rio Rancho, NM 87124');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_phone','505.994.6388');
INSERT INTO `settings` (`name`, `value`) VALUES ('stylesheet','mozilla');
INSERT INTO `settings` (`name`, `value`) VALUES ('phone_format','US - Loose');
INSERT INTO `settings` (`name`, `value`) VALUES ('date_format','English, US');
INSERT INTO `settings` (`name`, `value`) VALUES ('time_format','12 Hour');
INSERT INTO `settings` (`name`, `value`) VALUES ('currency_sym','$');
INSERT INTO `settings` (`name`, `value`) VALUES ('decimal_symbol','.');
INSERT INTO `settings` (`name`, `value`) VALUES ('thousands_separator',',');
INSERT INTO `settings` (`name`, `value`) VALUES ('currency_accuracy','2');
INSERT INTO `settings` (`name`, `value`) VALUES ('demo_enabled','false');
INSERT INTO `settings` (`name`, `value`) VALUES ('persistent_login','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('login_refresh','2');
--
INSERT INTO `settings` (`name`, `value`) VALUES ('application_uuid','');
INSERT INTO `settings` (`name`, `value`) VALUES ('auto_check_update','1');
INSERT INTO `settings` (`name`, `value`) VALUES ('send_metrics','0');
INSERT INTO `settings` (`name`, `value`) VALUES ('last_update_check','');