INSERT INTO `settings` (`name`, `value`) VALUES ('application_name','phpBMS');
INSERT INTO `settings` (`name`, `value`) VALUES ('encryption_seed','freeble');
INSERT INTO `settings` (`name`, `value`) VALUES ('record_limit','45');
INSERT INTO `settings` (`name`, `value`) VALUES ('default_load_page','modules/base/snapshot.php');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_name','Kreotek LLC');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_address','481 Rio Rancho Blvd. NE ');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_csz','Rio Rancho, NM 87124');
INSERT INTO `settings` (`name`, `value`) VALUES ('company_phone','505.994.6388');
INSERT INTO `settings` (`name`, `value`) VALUES ('stylesheet','mozilla');
INSERT INTO `settings` (`name`, `value`) VALUES ('phone_format','US - Loose');
INSERT INTO `settings` (`name`, `value`) VALUES ('date_format','English, US');
INSERT INTO `settings` (`name`, `value`) VALUES ('time_format','12 Hour');