CREATE TABLE recurringinvoices(
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoiceid` VARCHAR(64) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `until` DATE,
  `every` INTEGER UNSIGNED NOT NULL DEFAULT 1,
  `times` INTEGER UNSIGNED,
  `eachlist` VARCHAR(128),
  `ontheday` INTEGER UNSIGNED,
  `ontheweek` INTEGER UNSIGNED,
  `includepaymenttype` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `statusid` VARCHAR(64) NOT NULL,
  `assignedtoid` VARCHAR(64),
  `name` VARCHAR(255),
  `firstrepeat` DATE,
  `lastrepeat` DATE,
  `timesrepeated` INTEGER UNSIGNED NOT NULL DEFAULT 0,
  `notificationroleid` INTEGER UNSIGNED,
  PRIMARY KEY(`id`)
) ENGINE=INNODB;
